server {
    listen 8080 8081;  # Ports to listen on
    listen 8082;
	server_name server42.com;  # Server name
    root www;  # Root directory for the server
    index index.html;  # Default index file
    error_page 404 www/404.html;  # Custom 404 error page
    client_max_body_size 1000000000; # Maximum body size for client requests
    method GET POST;  # Allowed HTTP methods

    location / {
        try_files $uri $uri/ =404;  # Try to serve files, return 404 if not found
    }


    location /download/ {
        return 301 /files/;
    }

	location /files/ {
        autoindex on;  # Enable directory listing for /downloads/
	}

	location /nolist/ {
        autoindex off;
	}

    location /upload {
        root www/uploads;
		upload_path www/uploads;
        method POST;
		autoindex on;
        client_max_body_size 5000000; # Limit for uploads
    }

    location /delete {
        root www/uploads;
        method DELETE;
    }

    location /cgi-bin/ {
		root www/cgi-bin;
        cgi_enabled on;  # Enable CGI execution
        cgi .sh /bin/bash; # CGI script extension and interpreter
		cgi .py /usr/bin/python3;
		cgi .php /usr/bin/php;
    }
}

server {
	listen 8083;
	server_name pythonserver;
	root www/webpython;
	index index.py;
	client_max_body_size 500000;
	method GET;
	location / {
		root www/webpython;
		cgi_enabled on;
		cgi .py python3;
		try_files $uri $uri/ =404;
	}
}
