server {
    listen 8080 8081;  # Ports to listen on
    listen 8082;
	server_name server42.com;  # Server name
    root www;  # Root directory for the server
    index index.html;  # Default index file
    error_page 404 404.html;  # Custom 404 error page
    error_page 500 502 503 504 src/error_pages/50x.html;  # Custom 50x error pages
    client_max_body_size 1000000000; # Maximum body size for client requests
    method GET POST;  # Allowed HTTP methods

    location / {
        try_files $uri $uri/ =404;  # Try to serve files, return 404 if not found
    }

    location /images/ {
        return 301 /downloads/images/;  # Redirection
    }

    location /pictures/ {
        return 301 /downloads/images/;
    }

	location /downloads/ {
        autoindex on;  # Enable directory listing for /downloads/
	}

    location /upload/ {
        root test;
        method POST DELETE;
        client_max_body_size 50000000; # 50MB for uploads
    }

    location /delete/ {
        root test;
        method DELETE;
    }

    location /cgi-bin/ {
        cgi_enabled on;  # Enable CGI execution
        cgi .sh /bin/bash; # CGI script extension and interpreter
        include /etc/nginx/fastcgi_params;  # Include FastCGI parameters
        fastcgi_pass 127.0.0.1:9000;  # FastCGI server address
        fastcgi_index index.cgi;  # Default CGI script
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;  # Script filename
    }
}