server {
    listen 8085;
    server_name subject_test;
    root YoupiBanane;
    index index.html;
    client_max_body_size 1000000;

    location / {
        method GET;
        try_files $uri $uri/ =404;
    }

    location /put_test/ {
        method POST;
        root YoupiBanane/uploads;
        upload_path YoupiBanane/uploads;
        autoindex off;
        client_max_body_size 5000000;
    }

    location / {
        method POST;
        cgi_enabled on;
        cgi .bla ./ubuntu_cgi_tester;
        try_files $uri =404;
    }

    location /post_body {
        method POST;
        client_max_body_size 100;
        try_files /post_body =200;
    }

    location /directory/Yeah {
        method GET;
        autoindex on;
		try_files $uri $uri/Yeah =404;
        index youpi.bad_extension;
    }

    location /directory {
        method GET;
        root YoupiBanane;
        autoindex on;
		try_files $uri $uri/ =404;
        index youpi.bad_extension;
    }
}
